services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  portfolio-service:
    build:
      context: ./backend/alpaca
      dockerfile: Dockerfile
    container_name: portfolio-service-py
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - ALPACA_KEY=${ALPACA_KEY}
      - ALPACA_SECRET=${ALPACA_SECRET}
      - REDIS_HOST=redis  # Use the Redis container's name as the hostname